### ISSUE TITLE
Although `find_subtitles` requires Linux

### ISSUE THREAD

**Issue by scillidan** [directorscut82/find_subtitles#10]
Dud, can it work on windows 10?

I can run `subliminal`:

![image](https://github.com/user-attachments/assets/eb2bebd3-26de-45b3-acb4-b444eb7a3900)

But when use `find_subtitles.lua`, return:

![image](https://github.com/user-attachments/assets/5de00571-d56d-4a39-8e7f-cb82417f3879)

**Comment by directorscut82** [comment]
Never tested it so probably not, only Linux and it hasn't been maintained for years
  

  

  

  
  
  
  
>

**Comment by scillidan** [comment]
Thanks for your reply :)

With help of GPT-4, seems to be the problem with providers. Just edit `find_subtitle.lua`:

```
subliminal download --provider opensubtitles --provider podnapisi --provider thesubdb --provider tvsubtitles -l en -v
```

To:

```
subliminal download --provider opensubtitles --provider podnapisi --provider tvsubtitles -l en -v
```

It works well on Windows10.

![image](https://github.com/user-attachments/assets/49ee2e58-0c27-4bc7-b1cd-7fb1b87a92b2)
