### ISSUE TITLE
Is possible to choose a second language?

### ISSUE THREAD

**Issue by josecleiton** [directorscut82/find_subtitles#9]
I want to download subtitles from pt-BR, but if doesn't exist I accept english subs as well. There is a way to do this with the subliminal command? Thanks

**Comment by directorscut82** [comment]
Hi, if you take a look at subliminal's documentation, it seems that you can:
`  -l, --language LANGUAGE         Language as IETF code, e.g. en, pt-BR (can be used multiple times).  [required]`

Just add the languages you want in the script (line #38)
